using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using Bangazon_Financial.Factories;
using Bangazon_Financial.Entities;

namespace Bangazon_Financial_Tests
{
    //Class Name: ReportTests
    //Author: Grant Regnier
    //Purpose of the class: This Class tests the Report Type, and the interactions our factory preforms with the database.
    [TestClass]
    public class ReportTests
    {

        //Method Name: ReportsCanBeMade
        //Purpose of the Method: This method tests that there is a Report type, and that it has a name and price.
        [TestMethod]
        public void ReportsCanBeMade()
        {
            Report report = new Report();
            report.Name = "Fake Report";
            report.Price = 15.15;
            Assert.IsNotNull(report);
        }

        //Method Name: WeeklyReportsCanBeGenerated
        //Purpose of the Method: This method checks that a list of reports can be made with the GetWeeklyReports Method.
        [TestMethod]
        public void WeeklyReportsCanBeGenerated()
        {
            ReportFactory reportFactory = new ReportFactory();

            List<Report> WeeklyReport = new List<Report>();

            WeeklyReport = reportFactory.GetWeeklyReports();
            Assert.IsNotNull(WeeklyReport);
        }

        //Method Name: MonthlyReportsCanBeGenerated
        //Purpose of the Method: This method checks that a list of reports can be made with the GetMonthlyReports Method.
        [TestMethod]
        public void MonthlyReportsCanBeGenerated()
        {
            ReportFactory reportFactory = new ReportFactory();

            List<Report> MonthlyReport = new List<Report>();

            MonthlyReport = reportFactory.GetMonthlyReports();
            Assert.IsNotNull(MonthlyReport);
        }

        //Method Name: QuarterlyReportsCanBeGenerated
        //Purpose of the Method: This method checks that a list of reports can be made with the GetQuarterlyReports Method.
        [TestMethod]
        public void QuartlyReportsCanBeGenerated()
        {
            ReportFactory reportFactory = new ReportFactory();

            List<Report> QuarterlyReport = new List<Report>();
            QuarterlyReport = reportFactory.GetQuarterlyReports();
            Assert.IsNotNull(QuarterlyReport);
        }

        //Method Name: CanGetRevenueByCustomer
        //Purpose of the Method: This method Checks that a list of reports can be generated by the GetRevenueByCustomer.
        [TestMethod]
        public void CanGetRevenueByCustomer()
        {
            RevenueReportFactory revenueReportFactory = new RevenueReportFactory();

            List<Report> RevenueByCustomer = revenueReportFactory.GetRevenueByCustomer();

            Assert.IsTrue(RevenueByCustomer.Count > 0);
            Assert.IsNotNull(RevenueByCustomer);
        }

        //Method Name: CanGetRevenueByCustomer
        //Purpose of the Method: This method Checks that a list of reports can be generated by the GetRevenueByProduct.
        [TestMethod]
        public void CanGetRevenueByProduct()
        {
            RevenueReportFactory revenueReportFactory = new RevenueReportFactory();

            List<Report> RevenueByProduct = revenueReportFactory.GetRevenueByProduct();

            Assert.IsTrue(RevenueByProduct.Count > 0);
            Assert.IsNotNull(RevenueByProduct);
        }
    }
}
